services:
  matzipmap-be:
    image: gn0lee/matzipmap-api:latest
    container_name: matzipmap-be
    ports:
      - "8080:8080"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: always